
# Added by Gogh
include colors.conf
include layout.conf


mouse_map left click ungrabbed mouse_handle_click prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click link


allow_remote_control yes

# background_opacity 0.6
# background_blur 100
# dynamic_background_opacity yes
#

font_size        11.0
# window_padding_width 8

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
symbol_map U+0980-U+09FF Bornomala

# symbol_map_scale U+0980-U+09FF 0.85
# adjust_line_height 120%
# symbol_map U+0980-U+09FF Noto Sans Bengali
