enabled_layouts splits

map ctrl+shift+enter launch --location=vsplit --cwd=current
map alt+shift+enter launch --location=hsplit --cwd=current
map ctrl+alt+enter launch --location=split --cwd=current

map alt+shift+t launch --type=tab --cwd=current
map alt+shift+n launch --type=os-window --cwd=current


# Rotate the current split, changing its split axis from vertical to
# horizontal or vice versa
map alt+r layout_action rotate

---
# Resize the window
map ctrl+shift+l resize_window narrower
map ctrl+shift+h resize_window wider
map ctrl+shift+k resize_window taller
map ctrl+shift+j resize_window shorter 3

# reset all windows in the tab to default sizes
map ctrl+home resize_window reset

# Move the active window in the indicated direction
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

# Switch focus to the neighboring window in the indicated direction
map alt+shift+left neighboring_window left
map alt+shift+right neighboring_window right
map alt+shift+up neighboring_window up
map alt+shift+down neighboring_window down

# as vim keys
map alt+shift+h neighboring_window left
map alt+shift+l neighboring_window right
map alt+shift+k neighboring_window up
map alt+shift+j neighboring_window down

# Move the active window to the indicated screen edge
# map ctrl+shift+up layout_action move_to_screen_edge top
# map ctrl+shift+left layout_action move_to_screen_edge left
# map ctrl+shift+right layout_action move_to_screen_edge right
# map ctrl+shift+down layout_action move_to_screen_edge bottom

# Set the bias of the split containing the currently focused window. The
# currently focused window will take up the specified percent of its parent
# window's size.
map ctrl+shitf+. layout_action bias 80

# Maximize the active window along the horizontal axis (fill full width),
# keeping other windows visible in their vertical positions. Press again to
# restore the original layout.
map ctrl+shift+right layout_action maximize horizontal

# Maximize the active window along the vertical axis (fill full height),
# keeping other windows visible in their horizontal positions. Press again
# to restore the original layout.
map ctrl+shift+up layout_action maximize vertical
